version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: covid_db
    ports:
      - "3306:3306"
    networks:
      - covid-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: covid19-backend
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - covid-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: covid-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "4200:80"
    networks:
      - covid-network

networks:
  covid-network:

volumes:
  mysql-data:
