version: "3.8"

services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: covid_db
    ports:
      - "3307:3306"
    networks:
      - covid-network
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: covid19-backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: mysql-db
    networks:
      - covid-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: covid-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - covid-network

networks:
  covid-network:

volumes:
  mysql-data:
